name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Cambia la versión según tus necesidades

      - name: Install dependencies
        run: npm install # O el comando que uses para instalar dependencias

      - name: Build
        run: npm run build # O el comando que uses para construir tu app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Cambia esto a la carpeta donde se genera tu build